export const CEP_91520040 = {
  cep: "91520-030",
  logradouro: "Rua Borborema",
  complemento: "",
  unidade: "",
  bairro: "Vila João Pessoa",
  localidade: "Porto Alegre",
  uf: "RS",
  estado: "Rio Grande do Sul",
  regiao: "Sul",
  ibge: "4314902",
  gia: "",
  ddd: "51",
  siafi: "8801",
};

export const MULTIPLE_ADDRESSESS = [
  {
    cep: "91520-690",
    logradouro: "Rua Santa Maria",
    complemento: "(Vl São José Comunitária)",
    unidade: "",
    bairro: "Vila São José",
    localidade: "Porto Alegre",
    uf: "RS",
    estado: "Rio Grande do Sul",
    regiao: "Sul",
    ibge: "4314902",
    gia: "",
    ddd: "51",
    siafi: "8801",
  },
  {
    cep: "91520-460",
    logradouro: "Rua Santa Maria",
    complemento: "",
    unidade: "",
    bairro: "Vila São José",
    localidade: "Porto Alegre",
    uf: "RS",
    estado: "Rio Grande do Sul",
    regiao: "Sul",
    ibge: "4314902",
    gia: "",
    ddd: "51",
    siafi: "8801",
  },
];
